<!DOCTYPE html>
<html>
<head>
<title>Penggunaan Tag Tabel</title>
</head>
<body>
<h1>Usulan Judul</h1>
<table border="1">
    <tr>
        <td>NIM</td>
        <td>Golongan</td>
        <td>Prodi</td>
        <td>NIP</td>
        <td>Judul</td>
        <td>Judul Dosen</td>
        <td>Ringkasan</td>
        <td>Tugas</td>
        <td>Catatan</td>
        <td>Opsi</td>
    </tr>
    <tr>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td><button>Update</button><button>Delete</button></td>
    </tr>
    <tr>
         <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td><button>Update</button><button>Delete</button></td>
    </tr>
    <tr>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td>&nbsp</td>
        <td><button>Update</button><button>Delete</button></td>
    </tr>
</table><br>
     <button>Insert</button>
</body>
</html>